/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  sepolia: {
    MichiPayContract: {
      address:
        "0x2a03de72a8b5068c6e65428bd1db224c4cc9745f8a0d36116b89a2ad0ad361a",
      abi: [
        {
          type: "impl",
          name: "MichiPayImpl",
          interface_name: "contracts::michipayx::IMichiPay",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::michipayx::IMichiPay",
          items: [
            {
              type: "function",
              name: "create_session",
              inputs: [
                {
                  name: "total_amount",
                  type: "core::integer::u256",
                },
                {
                  name: "participants",
                  type: "core::array::Array::<core::starknet::contract_address::ContractAddress>",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u32",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "pay_share",
              inputs: [
                {
                  name: "session_id",
                  type: "core::integer::u32",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "claim_funds",
              inputs: [
                {
                  name: "session_id",
                  type: "core::integer::u32",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "strk_address",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::michipayx::MichiPayContract::SessionCreated",
          kind: "struct",
          members: [
            {
              name: "session_id",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "creator",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "total_amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::michipayx::MichiPayContract::SharePaid",
          kind: "struct",
          members: [
            {
              name: "session_id",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "participant",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::michipayx::MichiPayContract::FundsClaimed",
          kind: "struct",
          members: [
            {
              name: "session_id",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "creator",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::michipayx::MichiPayContract::Event",
          kind: "enum",
          variants: [
            {
              name: "SessionCreated",
              type: "contracts::michipayx::MichiPayContract::SessionCreated",
              kind: "nested",
            },
            {
              name: "SharePaid",
              type: "contracts::michipayx::MichiPayContract::SharePaid",
              kind: "nested",
            },
            {
              name: "FundsClaimed",
              type: "contracts::michipayx::MichiPayContract::FundsClaimed",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x761aa8da4547016c9684b756178c7fa12674dea27c10be193a944b7d79a867a",
    },
  },
} as const;

export default deployedContracts;
