/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  sepolia: {
    MichiPayContract: {
      address:
        "0x3d97fe98a952186f538fdada5fd49eecc07c42b4a2fdcffae0e770d941074e4",
      abi: [
        {
          type: "impl",
          name: "MichiPayImpl",
          interface_name: "contracts::michipayx::IMichiPay",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::michipayx::MichiSession",
          members: [
            {
              name: "creator",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "total_amount",
              type: "core::integer::u256",
            },
            {
              name: "amount_collected",
              type: "core::integer::u256",
            },
            {
              name: "is_active",
              type: "core::bool",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::michipayx::IMichiPay",
          items: [
            {
              type: "function",
              name: "create_session",
              inputs: [
                {
                  name: "total_amount",
                  type: "core::integer::u256",
                },
                {
                  name: "participants",
                  type: "core::array::Array::<core::starknet::contract_address::ContractAddress>",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u32",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "pay_share",
              inputs: [
                {
                  name: "session_id",
                  type: "core::integer::u32",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "claim_funds",
              inputs: [
                {
                  name: "session_id",
                  type: "core::integer::u32",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_user_debt",
              inputs: [
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_session",
              inputs: [
                {
                  name: "session_id",
                  type: "core::integer::u32",
                },
              ],
              outputs: [
                {
                  type: "contracts::michipayx::MichiSession",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_session_counter",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u32",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_session_debt",
              inputs: [
                {
                  name: "session_id",
                  type: "core::integer::u32",
                },
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_session_participants",
              inputs: [
                {
                  name: "session_id",
                  type: "core::integer::u32",
                },
              ],
              outputs: [
                {
                  type: "core::array::Array::<core::starknet::contract_address::ContractAddress>",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "strk_address",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::michipayx::MichiPayContract::SessionCreated",
          kind: "struct",
          members: [
            {
              name: "session_id",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "creator",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "total_amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::michipayx::MichiPayContract::SharePaid",
          kind: "struct",
          members: [
            {
              name: "session_id",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "participant",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::michipayx::MichiPayContract::FundsClaimed",
          kind: "struct",
          members: [
            {
              name: "session_id",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "creator",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::michipayx::MichiPayContract::Event",
          kind: "enum",
          variants: [
            {
              name: "SessionCreated",
              type: "contracts::michipayx::MichiPayContract::SessionCreated",
              kind: "nested",
            },
            {
              name: "SharePaid",
              type: "contracts::michipayx::MichiPayContract::SharePaid",
              kind: "nested",
            },
            {
              name: "FundsClaimed",
              type: "contracts::michipayx::MichiPayContract::FundsClaimed",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x613044d244cecff9e9c6450edf94c97e9ef69a6b23575d976be49bb66148076",
    },
  },
} as const;

export default deployedContracts;
